change the demo plot to a line plot
UBC-MDS/DSCI-532_2024_16_SilentEpidemic pull request #136
Opened 2024-04-17 06:44 UTC by billwan96

closes #126 
relates #135 (address the issue if all drug types are not selected)

2024-04-17 07:09 UTC, billwan96 commented
closes #115

2024-04-17 07:37 UTC, SoloSynth1 requested changes
@billwan96 Thanks for the PR, please see the comments.

2024-04-17 07:37 UTC, SoloSynth1 commented on src/modules/components/demo.py
> +                              (demo_df['Year'] <= selected_years[1])]
`demo_df['Year'].between()` would be a more succinct way to query this. Also, it seems line 23-24 and line 28-29 are doing the same thing. I would say it's better to break this filter into two parts, taking the year filter out of the if statement and do the `Drug Type` within.

2024-04-17 07:37 UTC, SoloSynth1 commented on src/modules/components/demo.py
> +            trace.line = dict(width=2.5)
I think we can make it even thicker. For now it does not have much difference than other lines.
![image](https://github.com/UBC-MDS/DSCI-532_2024_16_SilentEpidemic/assets/17952490/6cfa7570-721b-4c13-b887-65f75e41aede)

2024-04-17 18:30 UTC, billwan96 commented on src/modules/components/demo.py
> +            trace.line = dict(width=2.5)
thanks for the comments @SoloSynth1. As suggested I have changed the code for lines 22-24 and 28-29. I also increased the thickness of `Overall`. 

In addition, I recall we agreed to remove the `Non-Hispanic` word in the legend, I have also implemented this change

2024-04-18 18:21 UTC, SoloSynth1 commented on src/modules/components/demo.py
> +                              (demo_df['Year'] <= selected_years[1])]
Resolved in latest commit.

2024-04-18 18:21 UTC, SoloSynth1 commented on src/modules/components/demo.py
> +            trace.line = dict(width=2.5)
Resolved in latest commit.

2024-04-18 18:22 UTC, merged