add aggregated cards
UBC-MDS/DSCI-532_2024_16_SilentEpidemic pull request #60
Opened 2024-04-06 17:57 UTC by jinyz8888

The cards work but have different sizes. Tried to set them to be the same size, but didn't work, have no idea to optimize it.

2024-04-06 18:36 UTC, SoloSynth1 requested changes
@jinyz8888 Please see comments. I can see you commented out the `card` variable but I think it is still referenced in the `app.layout`. Have you tried to run the app? Did it render successfully?

I can also see for now the numbers are hardcoded to calculate fold between 2001 and 2015. No changes are needed for now but we definitely need to change it later on when we implement the filters.

2024-04-06 18:36 UTC, SoloSynth1 commented on src/app.py
> +    ], style=ROW_STYLE), """
Please remove the unused code block instead of commenting it out

2024-04-06 18:36 UTC, SoloSynth1 commented on src/app.py
> +]) """
`card` is still needed for placeholders.

2024-04-06 18:36 UTC, SoloSynth1 commented on src/app.py
> +# test_graph = dcc.Graph(id='example-graph', figure=fig)
Please remove the unused code instead of commenting it out
```suggestion
```

2024-04-06 18:36 UTC, SoloSynth1 commented on src/app.py
> +        style={"textAlign": "center", "color": "red"}
It would be best if you can combine the styles in this dictionary with the `CARD_STYLE`.

2024-04-06 18:36 UTC, SoloSynth1 commented on src/app.py
> +# fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")
Please remove the unused code instead of commenting it out.
```suggestion
```

2024-04-06 18:38 UTC, SoloSynth1 commented
@jinyz8888 As for the difference in card sizes, I would say don't worry about this for now. Later on we can make it more consistent via CSS.

2024-04-06 20:27 UTC, SoloSynth1 commented on src/app.py
> +    ], style=ROW_STYLE), """
Resolving this as the commented lines were removed in the latest commit.

2024-04-06 20:27 UTC, SoloSynth1 commented on src/app.py
> +]) """
Resolving this as the commented lines were removed in the latest commit.

2024-04-06 20:27 UTC, SoloSynth1 commented on src/app.py
> +# test_graph = dcc.Graph(id='example-graph', figure=fig)
Resolving this as the commented lines were removed in the latest commit.

2024-04-06 20:27 UTC, SoloSynth1 commented on src/app.py
> +# fig = px.bar(df, x="Fruit", y="Amount", color="City", barmode="group")
Resolving this as the commented lines were removed in the latest commit.

2024-04-07 00:45 UTC, SoloSynth1 commented
I have made the cards consistent in height, but it looks wack as the titles are too large. This will be fixed in another PR.

<img width="1258" alt="image" src="https://github.com/UBC-MDS/DSCI-532_2024_16_SilentEpidemic/assets/17952490/33040531-f0f2-4bee-a84a-223b3152fcdc">

2024-04-07 00:46 UTC, SoloSynth1 commented on src/app.py
> +        style={"textAlign": "center", "color": "red"}
extracted the styles and transferred them into an external CSS file. Resolving this.

2024-04-07 00:49 UTC, SoloSynth1 approved these changes
Let's merge it into `main` for now. The aggregated values are static right now so we have to create some callbacks during implementing the filters.

2024-04-07 00:50 UTC, merged

2024-04-07 00:50 UTC, SoloSynth1 commented
Merged into `main`. Thanks @jinyz8888 !

2024-04-07 00:51 UTC, jinyz8888 commented
Thanks @SoloSynth1 !