Update on the sidebar using different selection for sex and drug type
UBC-MDS/DSCI-532_2024_16_SilentEpidemic pull request #83
Opened 2024-04-10 20:33 UTC by billwan96

relates #74 
I have changed the sidebar wordings and selection type.
Joel suggested we to use checkboxes for sex, but I think the radio boxes are more user-friendly and easy to implement

2024-04-13 05:15 UTC, AlysenTownsley approved these changes
Looks good!

2024-04-13 17:28 UTC, AlysenTownsley requested changes

2024-04-13 17:28 UTC, AlysenTownsley commented on src/modules/components/sidebar.py
>                  value=['Any opioid', 'Prescription opioids', 'Synthetic opioids', 'Heroin',
Do we need to remove the 'any opioid' value here?

2024-04-13 17:54 UTC, jinyz8888 commented on src/modules/components/sidebar.py
>                  value=['Any opioid', 'Prescription opioids', 'Synthetic opioids', 'Heroin',
If no metrics are calculated on 'Any opioid', maybe we can remove it. Might need to evaluate the changes before and after removing it just in case unexpected weird numbers come out after removing it.

2024-04-13 17:57 UTC, billwan96 commented on src/modules/components/sidebar.py
>                  value=['Any opioid', 'Prescription opioids', 'Synthetic opioids', 'Heroin',
Yes, I think we should remove it.
Like @jinyz8888 said, though I know which part of the code of the demographic plot needs to be amended, I am not sure how will it impact some other graphs. I was therefore thinking we should fix it in a separate issue.

2024-04-14 06:39 UTC, AlysenTownsley commented on src/modules/components/sidebar.py
>                  value=['Any opioid', 'Prescription opioids', 'Synthetic opioids', 'Heroin',
Agreed. Thanks

2024-04-14 06:40 UTC, AlysenTownsley approved these changes

2024-04-14 08:29 UTC, SoloSynth1 commented
@billwan96 Is this PR still needed? I can see the commits were included in the branch `css_sidebar`, which was merged.

2024-04-14 08:42 UTC, billwan96 commented
> @billwan96 Is this PR still needed? I can see the commits were included in the branch `css_sidebar`, which was merged.

Yup, I guess this is no longer need! thanks

2024-04-14 08:42 UTC, closed without merging